//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace FitnessOfBand.WebService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Information", Namespace="http://car-sales-co.umbler.net/FitnessOfBand.asmx")]
    public partial class Information : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private int Wearable_IdField;
        
        private System.DateTime InitialDateTimeField;
        
        private System.DateTime FinishedDateTimeField;
        
        private int InitialHeartRateField;
        
        private int FinalHeartRateField;
        
        private long InitialDistanceField;
        
        private long FinalDistanceField;
        
        private long InitialStepsField;
        
        private long FinalStepsField;
        
        private long InitialCaloriesField;
        
        private long FinalCaloriesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Wearable_Id {
            get {
                return this.Wearable_IdField;
            }
            set {
                if ((this.Wearable_IdField.Equals(value) != true)) {
                    this.Wearable_IdField = value;
                    this.RaisePropertyChanged("Wearable_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime InitialDateTime {
            get {
                return this.InitialDateTimeField;
            }
            set {
                if ((this.InitialDateTimeField.Equals(value) != true)) {
                    this.InitialDateTimeField = value;
                    this.RaisePropertyChanged("InitialDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime FinishedDateTime {
            get {
                return this.FinishedDateTimeField;
            }
            set {
                if ((this.FinishedDateTimeField.Equals(value) != true)) {
                    this.FinishedDateTimeField = value;
                    this.RaisePropertyChanged("FinishedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int InitialHeartRate {
            get {
                return this.InitialHeartRateField;
            }
            set {
                if ((this.InitialHeartRateField.Equals(value) != true)) {
                    this.InitialHeartRateField = value;
                    this.RaisePropertyChanged("InitialHeartRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int FinalHeartRate {
            get {
                return this.FinalHeartRateField;
            }
            set {
                if ((this.FinalHeartRateField.Equals(value) != true)) {
                    this.FinalHeartRateField = value;
                    this.RaisePropertyChanged("FinalHeartRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public long InitialDistance {
            get {
                return this.InitialDistanceField;
            }
            set {
                if ((this.InitialDistanceField.Equals(value) != true)) {
                    this.InitialDistanceField = value;
                    this.RaisePropertyChanged("InitialDistance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public long FinalDistance {
            get {
                return this.FinalDistanceField;
            }
            set {
                if ((this.FinalDistanceField.Equals(value) != true)) {
                    this.FinalDistanceField = value;
                    this.RaisePropertyChanged("FinalDistance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public long InitialSteps {
            get {
                return this.InitialStepsField;
            }
            set {
                if ((this.InitialStepsField.Equals(value) != true)) {
                    this.InitialStepsField = value;
                    this.RaisePropertyChanged("InitialSteps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public long FinalSteps {
            get {
                return this.FinalStepsField;
            }
            set {
                if ((this.FinalStepsField.Equals(value) != true)) {
                    this.FinalStepsField = value;
                    this.RaisePropertyChanged("FinalSteps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public long InitialCalories {
            get {
                return this.InitialCaloriesField;
            }
            set {
                if ((this.InitialCaloriesField.Equals(value) != true)) {
                    this.InitialCaloriesField = value;
                    this.RaisePropertyChanged("InitialCalories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public long FinalCalories {
            get {
                return this.FinalCaloriesField;
            }
            set {
                if ((this.FinalCaloriesField.Equals(value) != true)) {
                    this.FinalCaloriesField = value;
                    this.RaisePropertyChanged("FinalCalories");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://car-sales-co.umbler.net/FitnessOfBand.asmx", ConfigurationName="WebService.FitnessOfBandSoap")]
    public interface FitnessOfBandSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://car-sales-co.umbler.net/FitnessOfBand.asmx/InsertWearable", ReplyAction="*")]
        System.Threading.Tasks.Task<FitnessOfBand.WebService.InsertWearableResponse> InsertWearableAsync(FitnessOfBand.WebService.InsertWearableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://car-sales-co.umbler.net/FitnessOfBand.asmx/GetWearable", ReplyAction="*")]
        System.Threading.Tasks.Task<FitnessOfBand.WebService.GetWearableResponse> GetWearableAsync(FitnessOfBand.WebService.GetWearableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://car-sales-co.umbler.net/FitnessOfBand.asmx/InsertInformation", ReplyAction="*")]
        System.Threading.Tasks.Task InsertInformationAsync(int Wearable_Id, System.DateTime InitialDateTime, System.DateTime FinishedDateTime, int InitialHeartRate, int FinalHeartRate, long InitialDistance, long FinalDistance, long InitialSteps, long FinalSteps, long InitialCalories, long FinalCalories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://car-sales-co.umbler.net/FitnessOfBand.asmx/GetInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<FitnessOfBand.WebService.GetInformationResponse> GetInformationAsync(FitnessOfBand.WebService.GetInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://car-sales-co.umbler.net/FitnessOfBand.asmx/GetLastInformations", ReplyAction="*")]
        System.Threading.Tasks.Task<FitnessOfBand.WebService.GetLastInformationsResponse> GetLastInformationsAsync(FitnessOfBand.WebService.GetLastInformationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://car-sales-co.umbler.net/FitnessOfBand.asmx/InsertRealTime", ReplyAction="*")]
        System.Threading.Tasks.Task InsertRealTimeAsync(int Wearable_Id, System.DateTime CapturedDateTime, int HeartRate, double Speed, double Pace, long TotalDistance, long TotalSteps, long Calories);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertWearableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertWearable", Namespace="http://car-sales-co.umbler.net/FitnessOfBand.asmx", Order=0)]
        public FitnessOfBand.WebService.InsertWearableRequestBody Body;
        
        public InsertWearableRequest() {
        }
        
        public InsertWearableRequest(FitnessOfBand.WebService.InsertWearableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://car-sales-co.umbler.net/FitnessOfBand.asmx")]
    public partial class InsertWearableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identification;
        
        public InsertWearableRequestBody() {
        }
        
        public InsertWearableRequestBody(string identification) {
            this.identification = identification;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertWearableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertWearableResponse", Namespace="http://car-sales-co.umbler.net/FitnessOfBand.asmx", Order=0)]
        public FitnessOfBand.WebService.InsertWearableResponseBody Body;
        
        public InsertWearableResponse() {
        }
        
        public InsertWearableResponse(FitnessOfBand.WebService.InsertWearableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertWearableResponseBody {
        
        public InsertWearableResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWearableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWearable", Namespace="http://car-sales-co.umbler.net/FitnessOfBand.asmx", Order=0)]
        public FitnessOfBand.WebService.GetWearableRequestBody Body;
        
        public GetWearableRequest() {
        }
        
        public GetWearableRequest(FitnessOfBand.WebService.GetWearableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://car-sales-co.umbler.net/FitnessOfBand.asmx")]
    public partial class GetWearableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Identification;
        
        public GetWearableRequestBody() {
        }
        
        public GetWearableRequestBody(string Identification) {
            this.Identification = Identification;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWearableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWearableResponse", Namespace="http://car-sales-co.umbler.net/FitnessOfBand.asmx", Order=0)]
        public FitnessOfBand.WebService.GetWearableResponseBody Body;
        
        public GetWearableResponse() {
        }
        
        public GetWearableResponse(FitnessOfBand.WebService.GetWearableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetWearableResponseBody {
        
        public GetWearableResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInformation", Namespace="http://car-sales-co.umbler.net/FitnessOfBand.asmx", Order=0)]
        public FitnessOfBand.WebService.GetInformationRequestBody Body;
        
        public GetInformationRequest() {
        }
        
        public GetInformationRequest(FitnessOfBand.WebService.GetInformationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://car-sales-co.umbler.net/FitnessOfBand.asmx")]
    public partial class GetInformationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        public GetInformationRequestBody() {
        }
        
        public GetInformationRequestBody(int Id) {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInformationResponse", Namespace="http://car-sales-co.umbler.net/FitnessOfBand.asmx", Order=0)]
        public FitnessOfBand.WebService.GetInformationResponseBody Body;
        
        public GetInformationResponse() {
        }
        
        public GetInformationResponse(FitnessOfBand.WebService.GetInformationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://car-sales-co.umbler.net/FitnessOfBand.asmx")]
    public partial class GetInformationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInformationResult;
        
        public GetInformationResponseBody() {
        }
        
        public GetInformationResponseBody(string GetInformationResult) {
            this.GetInformationResult = GetInformationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastInformationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastInformations", Namespace="http://car-sales-co.umbler.net/FitnessOfBand.asmx", Order=0)]
        public FitnessOfBand.WebService.GetLastInformationsRequestBody Body;
        
        public GetLastInformationsRequest() {
        }
        
        public GetLastInformationsRequest(FitnessOfBand.WebService.GetLastInformationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLastInformationsRequestBody {
        
        public GetLastInformationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastInformationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastInformationsResponse", Namespace="http://car-sales-co.umbler.net/FitnessOfBand.asmx", Order=0)]
        public FitnessOfBand.WebService.GetLastInformationsResponseBody Body;
        
        public GetLastInformationsResponse() {
        }
        
        public GetLastInformationsResponse(FitnessOfBand.WebService.GetLastInformationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://car-sales-co.umbler.net/FitnessOfBand.asmx")]
    public partial class GetLastInformationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<FitnessOfBand.WebService.Information> GetLastInformationsResult;
        
        public GetLastInformationsResponseBody() {
        }
        
        public GetLastInformationsResponseBody(System.Collections.ObjectModel.ObservableCollection<FitnessOfBand.WebService.Information> GetLastInformationsResult) {
            this.GetLastInformationsResult = GetLastInformationsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FitnessOfBandSoapChannel : FitnessOfBand.WebService.FitnessOfBandSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FitnessOfBandSoapClient : System.ServiceModel.ClientBase<FitnessOfBand.WebService.FitnessOfBandSoap>, FitnessOfBand.WebService.FitnessOfBandSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FitnessOfBandSoapClient() : 
                base(FitnessOfBandSoapClient.GetDefaultBinding(), FitnessOfBandSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.FitnessOfBandSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FitnessOfBandSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(FitnessOfBandSoapClient.GetBindingForEndpoint(endpointConfiguration), FitnessOfBandSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FitnessOfBandSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FitnessOfBandSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FitnessOfBandSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FitnessOfBandSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FitnessOfBandSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FitnessOfBand.WebService.InsertWearableResponse> FitnessOfBand.WebService.FitnessOfBandSoap.InsertWearableAsync(FitnessOfBand.WebService.InsertWearableRequest request) {
            return base.Channel.InsertWearableAsync(request);
        }
        
        public System.Threading.Tasks.Task<FitnessOfBand.WebService.InsertWearableResponse> InsertWearableAsync(string identification) {
            FitnessOfBand.WebService.InsertWearableRequest inValue = new FitnessOfBand.WebService.InsertWearableRequest();
            inValue.Body = new FitnessOfBand.WebService.InsertWearableRequestBody();
            inValue.Body.identification = identification;
            return ((FitnessOfBand.WebService.FitnessOfBandSoap)(this)).InsertWearableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FitnessOfBand.WebService.GetWearableResponse> FitnessOfBand.WebService.FitnessOfBandSoap.GetWearableAsync(FitnessOfBand.WebService.GetWearableRequest request) {
            return base.Channel.GetWearableAsync(request);
        }
        
        public System.Threading.Tasks.Task<FitnessOfBand.WebService.GetWearableResponse> GetWearableAsync(string Identification) {
            FitnessOfBand.WebService.GetWearableRequest inValue = new FitnessOfBand.WebService.GetWearableRequest();
            inValue.Body = new FitnessOfBand.WebService.GetWearableRequestBody();
            inValue.Body.Identification = Identification;
            return ((FitnessOfBand.WebService.FitnessOfBandSoap)(this)).GetWearableAsync(inValue);
        }
        
        public System.Threading.Tasks.Task InsertInformationAsync(int Wearable_Id, System.DateTime InitialDateTime, System.DateTime FinishedDateTime, int InitialHeartRate, int FinalHeartRate, long InitialDistance, long FinalDistance, long InitialSteps, long FinalSteps, long InitialCalories, long FinalCalories) {
            return base.Channel.InsertInformationAsync(Wearable_Id, InitialDateTime, FinishedDateTime, InitialHeartRate, FinalHeartRate, InitialDistance, FinalDistance, InitialSteps, FinalSteps, InitialCalories, FinalCalories);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FitnessOfBand.WebService.GetInformationResponse> FitnessOfBand.WebService.FitnessOfBandSoap.GetInformationAsync(FitnessOfBand.WebService.GetInformationRequest request) {
            return base.Channel.GetInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<FitnessOfBand.WebService.GetInformationResponse> GetInformationAsync(int Id) {
            FitnessOfBand.WebService.GetInformationRequest inValue = new FitnessOfBand.WebService.GetInformationRequest();
            inValue.Body = new FitnessOfBand.WebService.GetInformationRequestBody();
            inValue.Body.Id = Id;
            return ((FitnessOfBand.WebService.FitnessOfBandSoap)(this)).GetInformationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FitnessOfBand.WebService.GetLastInformationsResponse> FitnessOfBand.WebService.FitnessOfBandSoap.GetLastInformationsAsync(FitnessOfBand.WebService.GetLastInformationsRequest request) {
            return base.Channel.GetLastInformationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FitnessOfBand.WebService.GetLastInformationsResponse> GetLastInformationsAsync() {
            FitnessOfBand.WebService.GetLastInformationsRequest inValue = new FitnessOfBand.WebService.GetLastInformationsRequest();
            inValue.Body = new FitnessOfBand.WebService.GetLastInformationsRequestBody();
            return ((FitnessOfBand.WebService.FitnessOfBandSoap)(this)).GetLastInformationsAsync(inValue);
        }
        
        public System.Threading.Tasks.Task InsertRealTimeAsync(int Wearable_Id, System.DateTime CapturedDateTime, int HeartRate, double Speed, double Pace, long TotalDistance, long TotalSteps, long Calories) {
            return base.Channel.InsertRealTimeAsync(Wearable_Id, CapturedDateTime, HeartRate, Speed, Pace, TotalDistance, TotalSteps, Calories);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.FitnessOfBandSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.FitnessOfBandSoap)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/FitnessOfBand.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return FitnessOfBandSoapClient.GetBindingForEndpoint(EndpointConfiguration.FitnessOfBandSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return FitnessOfBandSoapClient.GetEndpointAddress(EndpointConfiguration.FitnessOfBandSoap);
        }
        
        public enum EndpointConfiguration {
            
            FitnessOfBandSoap,
        }
    }
}
